[service]
listen_addr = "${ADDR}"
listen_port = ${PORT}
secrets = "CYKABLYAT!"
session_limit = 0

[common]
doc_root = "./dist"

[log]
enable = true
path = "./logs"
prefix = "blyat_"


[db]
enable = false

[[room]]
id = 114514
name = "INM"
session_limit = 3
